version: 0.0
os: linux

files:
  - source: /script
    destination: /home/ubuntu/script/op
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/auth/deploy.sh
      timeout: 120
      runas: root
    - location: script/auth/switch.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: script/auth/valid.sh
      timeout: 60
      runas: root