version: 0.0
os: linux

files:
  - source: script/deploy.sh
    destination: /home/ubuntu/script/op/deploy.sh
    overwrite: yes
  - source: script/switch.sh
    destination: /home/ubuntu/script/op/switch.sh
    overwrite: yes
  - source: script/valid.sh
    destination: /home/ubuntu/script/op/valid.sh
    overwrite: yes
  - source: application.env
    destination: /home/ubuntu/env/op/application.env

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 120
      runas: root
    - location: script/switch.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: script/valid.sh
      timeout: 60
      runas: root