spring:
  profiles:
    include: dev
  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      globally_quoted_identifiers: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  jwt:
    secretKey:
      access: accesstest
      refresh: refreshtest