name: cd-prod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create application.yml
        run: |
          pwd
          cd ./operation-api/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" >> ./application-prod.yml
          cat ./application-prod.yml

      - name: Create application-test.yml
        run: |
          cd ./operation-domain/src/test
          mkdir -p resources
          touch ./resources/application-test.yml
          echo "${{ secrets.APPLICATION_DOMAIN_TEST }}" >> ./application-test.yml
          cat ./application-test.yml

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.AWS_BUCKET_NAME }}/prod/deploy/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name operation
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name prod
          --s3-location bucket=${{ secrets.AWS_BUCKET_NAME }},bundleType=zip,key=prod/deploy/$GITHUB_SHA.zip