name: ci-prod

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: 'Create application.yml'
        run: |
          echo "${{ secrets.APPLICATION_PROD }}" > src/main/resources/application-prod.yml
          cat src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash