name: ci

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create application.yml
        run: |
          pwd
          cd ./operation-api/src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.APPLICATION_DEV }}" >> ./application-dev.yml
          cat ./application-dev.yml

      - name: 'Get key from Github Secrets'
        run: |
          pwd
          mkdir -p ./operation-api/src/main/resources/static
          echo "${{ secrets.APPLE_KEY }}" | base64 -d > ./operation-api/src/main/resources/static/${{ secrets.APPLE_KEY_NAME }}

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash