name: ci

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Get application.yml from AWS S3'
        run: |
          aws s3 cp \
            --region ${{ secrets.AWS_REGION }} \
            s3://${{ secrets.AWS_BUCKET_NAME }}/dev/deploy/application-dev.yml src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash